### ISSUE TITLE
UllageSimulator

### ISSUE THREAD

**Issue by Swamp-Ig** [HoneyFox/EngineIgnitor#1]
Just been looking through your code, noticed a bug:

public void Reset()
        {
            **ullageHeightMax** = 0.05f; ullageHeightMax = 0.95f;
            ullageRadialMin = 0.0f; ullageRadialMax = 0.95f;
        }

Shouldn't this read ullageHeightMin ?
In any case, setting the max twice isn't what you're intending I'm sure :smile:

**Comment by HoneyFox** [comment]
:+1: Yes, that's a typo and is fixed in latest revision. Thanks.
